ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 650
TOTAL_LEVELS = 10

#enemy constants
SPAWN_COOLDOWN = 600
MISSED_ENEMY_COST = 10 # MAY BE FOR EACH TYPE

DAMAGE_TURRET_1 = 10
DAMAGE_TURRET_2 = 20
DAMAGE_TURRET_3 = 40
DAMAGE_TURRET_4 = 60

UPGRADE_COST_1 = 150 
UPGRADE_COST_2 = 250
UPGRADE_COST_3 = 300
UPGRADE_COST_4 = 400

#turret constants
TURRET_LEVELS = 4
BUY_COST = 200


KILL_REWARD_WEAK = 10
KILL_REWARD_MED = 20
KILL_REWARD_STR = 40
KILL_REWARD_ELI = 60


KIlL_HEALTH_REWARD_WEAK = 1
KIlL_HEALTH_REWARD_MEDIUM = 2
KIlL_HEALTH_REWARD_STRONG = 3
KIlL_HEALTH_REWARD_ELITE = 4

MISED_HEALTH_RETRIEVE = 5


LEVEL_COMPLETE_REWARD = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
